server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: adg123
    username: root
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=UTC
  rabbitmq:
    virtual-host: /leyou
    host: 120.76.202.237
    username: admin
    password: xufushen
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: org.Mercury.entity


